services:
  app:
    build: .
    restart: unless-stopped
    env_file: .env.local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fodi-eyes.rule=Host(`fodi-eyes.fodivps2.cloud`)"
      - "traefik.http.routers.fodi-eyes.entrypoints=websecure"
      - "traefik.http.routers.fodi-eyes.tls.certresolver=letsencrypt"
      - "traefik.http.services.fodi-eyes.loadbalancer.server.port=3000"
    networks:
      - traefik-public
      - panel-internal

networks:
  traefik-public:
    external: true
  panel-internal:
    external: true
